version: '2'

services:
  api:
    build: ./
    restart: always
    environment:
      MYSQL_URL: mysql://root:root@mysql:3306/ganjoor
    ports:
      - "4003:4003"
    links:
      - db:mysql
    depends_on:
      - db

  db:
    build: ./docker/db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ganjoor
